baseURL = "https://pei0804.github.io/profile/"
publishDir = "docs"
title = "pei0804"
theme = "hugo-coder"
languagecode = "ja"
defaultcontentlanguage = "ja"

paginate = 20

[services]
[services.disqus]
disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Jumpei 'pei0804' Chikamori"
  info = "Data Engineer"
  description = "pei0804's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://avatars.githubusercontent.com/u/9821370"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/pei0804/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/pei0804/"
[[params.social]]
  name = "Speakerdeck"
  icon = "fa-brands fa-speaker-deck fa-2x"
  weight = 3
  url = "https://speakerdeck.com/pei0804"
[[params.social]]
  name = "Zenn"
  icon = "fa-solid fa-book fa-2x"
  weight = 3
  url = "https://zenn.dev/pei0804"